[mypy]
python_version = 3.12
mypy_path = src
explicit_package_bases = True
ignore_missing_imports = True
no_implicit_optional = False
follow_imports = normal

[mypy-tests.*]
ignore_errors = True

[mypy-pytest]
ignore_missing_imports = True
